uid: 019f6987-0d57-7e80-ae37-c4a533a6dfdf
name: 'Product Anonymous Melbourne'
summary: 'A community for product practitioners sharing practical product-management, design, and research experience.'
description: 'Product Anonymous Melbourne brings product practitioners together to share practical product-management, design, and research experience.'
topics: ['software-engineering']
eventTypes: ['meetup']
websiteUrl: 'https://www.meetup.com/product-anonymous-meetup-melbourne/'
eventsUrl: 'https://www.meetup.com/product-anonymous-meetup-melbourne/events/'
location: 'Melbourne'
eventsFetchedAt: '2026-07-24T12:34:35.000Z'
communityFirst: true
