uid: 01a031d4-6a28-7341-a5a0-50e6f2c177be
title: 'Beaudan Campbell-Brown - Nix in a Nutshell'
start: '2026-09-17T18:00:00+10:00'
end: '2026-09-17T20:00:00+10:00'
group: 'melbourne-compose'
topics: ['haskell', 'scala', 'software-engineering', 'open-source']
eventType: 'meetup'
paid: false
format: 'in-person'
venue: 'kathleen-syme-library-carlton'
url: 'https://luma.com/q1rremzi'
